version: '3.9'

services:
  grpc-server:
    build:
      context: ./grpc-server
    container_name: grpc-server
    hostname: grpc-server
    restart: always
    environment:
      LISTEN_PORT: "9000"
      LISTEN_PORT_TLS: "9443"
      # GRPC_VERBOSITY: "debug"
      # GRPC_TRACE: all
  grpc-client:
    build:
      context: ./grpc-client
    container_name: grpc-client
    hostname: grpc-client
    restart: always
    environment:
      USE_TLS: "false"
      ENDPOINT: "grpc-server:9000"
      # GRPC_VERBOSITY: "debug"
      # GRPC_TRACE: all
  grpc-client-tls:
    build:
      context: ./grpc-client
    container_name: grpc-client-tls
    hostname: grpc-client-tls
    restart: always
    environment:
      USE_TLS: "true"
      ENDPOINT: "grpc-server:9443"
      GRPC_DEFAULT_SSL_ROOTS_FILE_PATH: "/app/ca.crt.pem"
      # GRPC_VERBOSITY: "debug"
      # GRPC_TRACE: all
  fastapi-hypercorn:
    build:
      context: ./fastapi
    container_name: fastapi-hypercorn
    hostname: fastapi-hypercorn
    restart: always
    environment:
      SERVER_TYPE: "hypercorn"
      SERVER_PORT: "8081"
  fastapi-uvicorn:
    build:
      context: ./fastapi
    container_name: fastapi-uvicorn
    hostname: fastapi-uvicorn
    restart: always
    environment:
      SERVER_TYPE: "uvicorn"
      SERVER_PORT: "8081"
  debug:
    build:
      context: ./debug
    container_name: debug
    hostname: debug
    restart: always
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - |
        while true; do
          echo "`date +"%Y-%m-%d %H:%M:%S"`  Debug Container.."
          sleep 1;
        done