apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  terminationGracePeriodSeconds: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
  containers:
    - name: debug
      image: seemscloud/debug:latest
      imagePullPolicy: Always
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        allowPrivilegeEscalation: true
        privileged: true
