apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  terminationGracePeriodSeconds: 1
  securityContext:
    runAsNonRoot: false
    runAsUser: 1
    runAsGroup: 1
    fsGroup: 1
  containers:
    - name: debug
      image: seemscloud/debug:latest
      imagePullPolicy: Always
      securityContext:
        runAsNonRoot: false
        runAsUser: 1
        runAsGroup: 1
        allowPrivilegeEscalation: true
        privileged: true
