name: "Build Container Debug"

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      #      - name: Login to Docker Hub
      #        uses: docker/login-action@v3
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #      - uses: docker/build-push-action@v2
      #        with:
      #          push: true
      #          context: debug
      #          tags: seemscloud/debug:latest
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: 'Get tag'
        id: tag
        uses: 'WyriHaximus/github-action-get-previous-tag@8a0e045f02c0a3a04e1452df58b90fc7e555e950'

      - name: Set correct environment
        run: |
          TAG=${{ steps.tag.outputs.tag }}
          echo "TAG=$TAG" >> "$GITHUB_ENV"