name: "build-debug"

on:
  push:
    tags:
      - '[a-z0-9]+-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: debug
            dockerfile: Dockerfile
          - image: k3s
            dockerfile: Dockerfile
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: ./images/${{ matrix.image }}
          file: ./images/${{ matrix.image }}/${{ matrix.dockerfile }}
          tags: seemscloud/${{ matrix.image }}:latest
  #  versioning:
  #    steps:
  #      - name: Checkout the Repository
  #        uses: actions/checkout@v2

  #      - name: Versioning
  #        id: versioning
  #        run: |
  #          for i in `ls -d1 "${PWD}"/images/*` ; do
  #            echo $i
  #          done
  #

  #      - uses: docker/build-push-action@v2
  #        with:
  #          push: true
  #          context: debug
  #          tags: seemscloud/debug:${{ steps.versioning.outputs.LATEST_TAG }}
  #          git config --global user.name 'Versioning'
  #          git config --global user.email 'contact@seems.cloud'
  #          git commit -am "Automated report"
  #          git push




#          git config --global user.name 'Versioning'
#          git config --global user.email 'contact@seems.cloud'
#          git commit -am "Automated report"
#          git push