name: "build-debug"

on:
  push:
    tags:
      - '[a-z0-9]+-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  images:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: "seemscloud"
    strategy:
      matrix:
        include:
          - image: debug
            dockerfile: Dockerfile
          - image: k3s
            dockerfile: Dockerfile
          - image: grpc-client
            dockerfile: Dockerfile
          - image: grpc-server
            dockerfile: Dockerfile
          - image: grpc-xds-server
            dockerfile: Dockerfile
          - image: fastapi
            dockerfile: Dockerfile
    steps:
      - name: "[Checkout] Build"
        uses: actions/checkout@v2
        with:
          path: build
      - name: "[Checkout] Helpers"
        uses: actions/checkout@v2
        with:
          repository: seemscloud/github-actions-helpers
          path: helpers
      - name: "[Login] Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "[Script] Get Version Tag"
        id: versioning
        run: |
          cd build
          /bin/bash ${GITHUB_WORKSPACE}/helpers/ci/get-tag.sh ${{ matrix.image }}
      - name: "[Checkout] Build to Tag"
        uses: actions/checkout@v2
        with:
          path: build
          ref: ${{ steps.versioning.outputs.VERSION_TAG }}
      - name: "[Script] Docker Build & Push & Version"
        run: |
          cd build/${{ matrix.image }}
          
          /bin/bash ${GITHUB_WORKSPACE}/helpers/ci/docker/build-push-version.sh ${{ matrix.image }} ${{ steps.versioning.outputs.VERSION_TAG }}