name: "build-debug"

on:
  push:
    tags:
      - '[a-z0-9]+-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      LATEST_TAG: ${{ steps.versioning.outputs.LATEST_TAG }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Versioning
        id: versioning
        run: /bin/bash .github/scripts/get-latest-tag.sh
  #      - name: Login to Docker Hub
  #        uses: docker/login-action@v3
  #        with:
  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #      - uses: docker/build-push-action@v2
  #        with:
  #          push: true
  #          context: debug
  #          tags: seemscloud/debug:${{ steps.versioning.outputs.LATEST_TAG }}
  build-debug:
    runs-on: ubuntu-latest
    needs: [ versioning ]
    steps:
      - name: Tests
        env:
          VERSION_TAG: ${{ needs.versioning.outputs.LATEST_TAG }}
        id: versioning
        run: echo "${VERSION_TAG}"
#      - name: Check out the repo
#        uses: actions/checkout@v2
#      - name: Versioning
#        id: versioning
#        run: |
#          cd images/debug
#
#          git config --global user.name 'Versioning'
#          git config --global user.email 'contact@seems.cloud'
#          git commit -am "Automated report"
#          git push